name: Backend > CI
on:
  pull_request:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.5"
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "backend/pyproject.toml"
      - name: Setup project
        run: uv sync --locked --all-extras --dev
      - name: Run tests and save reports
        run: |
          uv run pytest \
          --doctest-modules \
          --junitxml=junit/test-results.xml \
          --cov=com \
          --cov-report=xml \
          --cov-report=html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: test-results
          path: junit/test-results.xml
